apiVersion: v1
kind: ServiceAccount
metadata:
  name: novasurge-sa
  namespace: shopfusion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novasurge-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - pods/exec
  - pods/status
  - services
  - endpoints
  - configmaps
  - namespaces
  - nodes
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: novasurge-binding
subjects:
- kind: ServiceAccount
  name: novasurge-sa
  namespace: shopfusion
roleRef:
  kind: ClusterRole
  name: novasurge-role
  apiGroup: rbac.authorization.k8s.io
