fullnameOverride: postgres-service

auth:
  username: novasurge
  password: novasurge123
  database: productsdb

primary:
  initdb:
    scripts:
      grant_productsdb.sql: |
        GRANT ALL PRIVILEGES ON DATABASE productsdb TO novasurge;

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  persistence:
    enabled: true
    size: 5Gi

service:
  type: ClusterIP
  port: 5432
